### ISSUE TITLE
CUDA implementation

### ISSUE THREAD

**Issue by Maghoumi** [Sleepwalking/pytorch-softdtw#6]
Thanks again for your implementation! 

Just wanted to let you know that I just released a fast CUDA implementation that's based on your code: https://github.com/Maghoumi/pytorch-softdtw-cuda

I made sure to give you credit and include a link to your repo wherever I included your CPU implementation. If there's any other note in particular that you'd like me to include, please let me know.

**Comment by Sleepwalking** [comment]
Hello Maghoumi,

Thank you very much for the CUDA version. I am very happy that my little snippet could be of some use : )

I am also very curious about how it works. Did a quick scan through the GPU DTW paper, and saw that the main concept is to take advantage of independence among anti-diagonal elements of the `R` matrix. I haven't used `cuda.jit` so I guess `b = cuda.blockIdx.x` and `tid = cuda.threadIdx.x` are semantically same as vectorization?

If that indeed is the case, I wonder what would cause the restriction that the sequences to be compared must have equal length?

Thanks.

**Comment by Maghoumi** [comment]
Hey, no problem!

> I guess b = cuda.blockIdx.x and tid = cuda.threadIdx.x are semantically same as vectorization?

Sort of. Think of `b` as the accessor to the batch, and `tid` as a row/column accessor into that batch's distance matrix. When the function is running, you'd have as many `b`s as your batches, and as many `tid`s as your sequences's length simultaneously. That way you can do `b` x `tid` operations in parallel.

> If that indeed is the case, I wonder what would cause the restriction that the sequences to be compared must have equal length?

There is nothing that'd fundamentally prevent us from being able to process different lengths. It's just that I haven't implemented it yet!! I did this implementation a while back (around the time when I sent you the batch support PR). Hopefully, once I get a chance, I'll add the support for different length sequences too.

**Comment by Maghoumi** [comment]
Actually, I just realized that adding support for sequences of different lengths was easily possible in my current code. I just pushed a commit that adds this support, and results seem to match with your CPU implementation.

**Comment by Sleepwalking** [comment]
This is awesome! I played a little bit with your implementation and it certainly runs fast.

https://github.com/Sleepwalking/pytorch-softdtw/commit/ddff7e3237a3520711f5b48b9e1ffc4647e9ef4a Readme updated with cross references.
